#!/usr/bin/env ruby
if `grep -rls "debugger" *` != ""
  puts "You twit, you've left a debugger in!"
  exit(1)
end
if `grep -rls "binding.pry" *` != ""
  puts "You twit, you've left a debugger in!"
  exit(1)
end
if `grep -rls "focus: true" *` != ""
  puts "You twit, you've left focus in"
  exit(1)
end
if `egrep -rls "^<<<<<<< |^>>>>>>> |^=======$" * | xargs file | egrep 'script|text'` != ""
  puts "Dang, looks like you screwed the merge!"
  puts `egrep -rls "^<<<<<<< |^>>>>>>> |^=======$" * | xargs file | egrep 'script|text' | awk -F: '{print $1}'`
  exit(1)
end
