#!/usr/bin/env ruby
# vim: set syntax=ruby

flag = false

files = `git diff --cached --name-only --diff-filter=ACM | grep "_spec\.rb$"`.split("\n")
files.each do |file|
  results = `git diff --cached  #{file} | grep "^\+[^+]" | grep -e "binding.pry" -e "focus: true" -e ":focus => true" -e "console.log" -e "debugger"`.split("\n").map { |r| r.sub(/^\+[\s\t]*/, '') }

  if $? == 0
    puts file
    puts results.map { |r|
      `grep -n "#{r}" #{file}`
    }.join("")
    puts "Please remove binding.pry and :focus => true from your test before committing"
    flag = true
  end
end

exit 1 if flag
